metro_data = {
    "victoria": {"pos": (50, 20), "neighbors": ["sidi bishr"]},
    "sidi bishr": {"pos": (40, 55), "neighbors": ["victoria", "el saraya"]},
    "el saraya": {"pos": (40, 90), "neighbors": ["sidi bishr", "loran"]},
    "loran": {"pos": (40, 125), "neighbors": ["el saraya", "tharwat"]},
    "tharwat": {"pos": (40, 160), "neighbors": ["loran", "san stefano"]},
    "san stefano": {"pos": (40, 195), "neighbors": ["tharwat", "kasr el safa", "janaklees"]},
    "kasr el safa": {"pos": (40, 230), "neighbors": ["san stefano", "fnoun gmeela"]},
    "fnoun gmeela": {"pos": (42, 265), "neighbors": ["kasr el safa", "gleem"]},
    "gleem": {"pos": (44, 300), "neighbors": ["fnoun gmeela", "elbostaan"]},
    "elbostaan": {"pos": (46, 335), "neighbors": ["elhadaya", "gleem"]},
    "elhadaya": {"pos": (49, 370), "neighbors": ["elbostaan", "bokla"]},
    "janaklees": {"pos": (90, 210), "neighbors": ["san stefano", "sheds"]},
    "sheds": {"pos": (135, 230), "neighbors": ["janaklees", "safr"]},
    "safr": {"pos": (145, 265), "neighbors": ["sheds", "bakoos"]},
    "bakoos": {"pos": (135, 300), "neighbors": ["safr", "flemeng"]},
    "flemeng": {"pos": (130, 335), "neighbors": ["bakoos", "el wezara"]},
    "el wezara": {"pos": (125, 370), "neighbors": ["flemeng", "bokla"]},
    "bokla": {"pos": (83, 405), "neighbors": ["el wezara", "roshdi"]},
    "roshdi": {"pos": (83, 440), "neighbors": ["bokla", "mo.mahfouz"]},
    "mo.mahfouz": {"pos": (83, 475), "neighbors": ["roshdi", "mostafa kamel"]},
    "mostafa kamel": {"pos": (83, 510), "neighbors": ["sidi gaber", "*", "mo.mahfouz"]},
    "sidi gaber": {"pos": (133, 535), "neighbors": ["mostafa kamel", "zanaziri"]},
    "zanaziri": {"pos": (123, 570), "neighbors": ["sidi gaber", "sporting elkobra"]},
    "sporting elkobra": {"pos": (103, 650), "neighbors": ["zanaziri", "sporting elsoghra", "cleopatra elsoghra"]},
    "*": {"pos": (90, 545), "neighbors": ["mostafa kamel", "^"]},
    "^": {"pos": (90, 580), "neighbors": ["*", "cleopatra elsoghra"]},
    "cleopatra elsoghra": {"pos": (90, 615), "neighbors": ["^", "sporting elkobra"]},
    "sporting elsoghra": {"pos": (103, 685), "neighbors": ["sporting elkobra", "ibrahimiya"]},
    "ibrahimiya": {"pos": (103, 720), "neighbors": ["sporting elsoghra", "elshatbi"]},
    "elshatbi": {"pos": (103, 755), "neighbors": ["ibrahimiya"]}
}